#!/bin/sh

ls /sys/block/zram* > /dev/null 2>&1 || exit 0

for i in /sys/block/zram*; do
	read orig compr rest < $i/mm_stat
	ratio=0
	if [ $compr -gt 0 ]; then
		ratio=$(echo "scale=2; $orig*100/$compr" | bc -q)
	fi
	echo -e "/dev/${i/*\/}:\t$ratio% ($orig -> $compr)"
done
